volumes:
  psql:
  caddy-config:
  caddy-data:

services:
  psql:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  switchers:
    build: .
    depends_on:
      - psql
    restart: unless-stopped
    ports:
      - 8000:8000

  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
     - 80:80
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/dist:/usr/share/caddy
      - ./caddy/public:/usr/share/caddy/public